### ISSUE TITLE
Unable to Find XenAPI Object

### ISSUE THREAD

**Issue by MastefChief** [cadox8/XenAPI#10]
While in my Java IDE (Intellij), when I try to type "XenAPI" nothing comes up as if the package cannot be found. I have added the jar as a dependency to my project but cant seem to access anything from XenAPI. Please Advise.

**Comment by cadox8** [comment]
Should be fixed on v0.4.4
Get it from [here ](https://github.com/cadox8/XenAPI/releases/tag/0.4.4) or add this in your pom.xml

```xml
    <repositories>
        <repository>
            <id>XenAPI Repo</id>
            <url>https://cadox8.github.io/repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>me.cadox8</groupId>
            <artifactId>XenAPI</artifactId>
            <version>0.4.4</version>
        </dependency>
    </dependencies>
```

**Comment by MastefChief** [comment]
A side question but is their a ETA for Full Java API for Xenforo 2?

**Comment by cadox8** [comment]
I have the plan to release it on April 19-20
