### ISSUE TITLE
GET_ALERTS parse error?

### ISSUE THREAD

**Issue by SkyLicks** [cadox8/XenAPI#12]
**Describe the bug**
There is an error getting an API reply in GET_ALERTS.

**To Reproduce**
```
public static void handleTickets() {
        Request r = RequestBuilder.newRequest(RequestType.GET_ALERTS)
                .addParam(RequestParam.VALUE_STRING, "Information")
                .addParam(RequestParam.TYPE_STRING, "fetchAll")
                .createRequest();

        System.out.println(r.getURL(XenAPI.getInstance()));

        XenAPI.getInstance().getReply(r, (Callback<AuthenticateReply>) (failCause, result) -> {
            try {
                if (failCause != null) {
                    failCause.printStackTrace();
                } else {
                    Logs.log(result.toString());
                }
            } catch (ArgsErrorException e) {
                e.printStackTrace();
            }
        });
    }
```

**Expected behavior**
If I print the request url, and paste it in my browser, that seems to work fine so I know didn't make any request errors. It appears there is some issue here during the parsing of that result.

**Screenshots**
![image](https://user-images.githubusercontent.com/34877092/84331856-5ed9ea00-ab59-11ea-9f79-351514ecedbf.png)

**Comment by cadox8** [comment]
Hello @SkyLicks and sorry for not answering until today, I was rewriting some parts of the code and documentation.

I can see you're trying to get Alerts but the Callback you're using is **AuthenticateReply**. 
Can you, please, change it to [AlertsReply](https://github.com/cadox8/XenAPI/blob/master/src/me/cadox8/xenapi/reply/AlertsReply.java) and test it?
Also we have a "[new documentation](https://cadox8.github.io/XenAPI/)" (that will be more complete in a future) if you need more help.

**Comment by cadox8** [comment]
Also, check the updated docs of [Get Alerts](https://cadox8.github.io/XenAPI/#/actions/get_alerts)
