### ISSUE TITLE
Xenforo 2.0

### ISSUE THREAD

**Issue by Bobsilvio** [cadox8/XenAPI#13]
hello, will there ever be a version for 2.0?
i rooted the forum and extras too based on these bees.
I'm stuck at xenforo 1.x version waiting for updates of these api for xenforo 2.0.
Will the new version come out?
I might as well pay.

**Comment by cadox8** [comment]
Hello and sorry for this late answer.

Xenforo 2.X has a native [Rest API ](https://xenforo.com/xf2-docs/dev/rest-api/). A Java and TypeScript wrapper for that is comming in about 1-2 week(s).

**Comment by Bobsilvio** [comment]
thanks, i love your api for xenforo 1.x. i use a php versione. Yes i now.but i based the software on your api, and if i change, the old versions stop working

**Comment by Bobsilvio** [comment]
news?

**Comment by cadox8** [comment]
#15
