### ISSUE TITLE
[Question] Will this work for cloud flare?

### ISSUE THREAD

**Issue by AdriaanBoshoff** [cadox8/XenAPI#4]
I wanted to test the xenforo 2.0 branch to see if the authentication at least works. I'm unsure if it's the api that doesn't work or if it is cloudflare blocking it.

![restdebugger_2018-06-21_09-48-15](https://user-images.githubusercontent.com/16230645/41705105-537625ce-7538-11e8-9068-e154881c8eb6.png)

**Comment by cadox8** [comment]
CloudFlare should not interfere with anything. XenAPI for Xenforo 2.X is in development, as can be seen here:
![Gyazo](https://i.gyazo.com/7beb9794cd1aa91ca2883a2bcd01de00.png)

I have created a Issue (with a Milestone) to release the XenAPI for Xenforo 2.X before that day (#5)

**Comment by AdriaanBoshoff** [comment]
Sorry. I didn't know what it meant when it says internal error. I thought that cloudflare was responsible.
